/* DO NOT EDIT THIS FILE - it is machine generated */
#include "platform.h"
#ifdef  WIN_PLATFORM


#else
#include <jni.h>
/* Header for class ffmpeg_playVideo */

#ifndef _Included_ffmpeg_playVideo
#define _Included_ffmpeg_playVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ffmpeg_playVideo
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_playVideo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    setAllparamer
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_setAllparamer
  (JNIEnv *, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    setSuface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_setSuface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    setOneframe
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_setOneframe
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ffmpeg_playVideo
 * Method:    addTrackers
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_addTrackers
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ffmpeg_playVideo
 * Method:    tracking
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_tracking
  (JNIEnv *, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    updateAndShow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_updateAndShow
  (JNIEnv *, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    deleteTrackers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_deleteTrackers
  (JNIEnv *, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    deleteRects
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_deleteRects
  (JNIEnv *, jobject);

/*
 * Class:     ffmpeg_playVideo
 * Method:    count_frame_start
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ffmpeg_playVideo_count_1frame_1start
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
#endif

