//
// Created by wangry on 2019/11/11.
//

#ifndef ANDROID_COMPUTERVISIONPROJECT_MASTER_PLATFORM_H
#define ANDROID_COMPUTERVISIONPROJECT_MASTER_PLATFORM_H

#define WIN_PLATFORM

#endif //ANDROID_COMPUTERVISIONPROJECT_MASTER_PLATFORM_H
